version: '3.7'

services:
  postgres:
    container_name: hibernate-starter
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-hibernate_starter}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5434:5432'
